# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'word_note_generator0.3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(365, 398)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_input = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_input.setGeometry(QtCore.QRect(10, 139, 341, 181))
        self.textEdit_input.setObjectName("textEdit_input")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(230, 109, 75, 23))
        self.pushButton_start.setObjectName("pushButton_start")
        self.radioButton_file = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_file.setGeometry(QtCore.QRect(110, 69, 89, 16))
        self.radioButton_file.setObjectName("radioButton_file")
        self.radioButton_clipboard = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_clipboard.setGeometry(QtCore.QRect(110, 99, 89, 16))
        self.radioButton_clipboard.setObjectName("radioButton_clipboard")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 19, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 19, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 19, 2, 2))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(40, 29, 155, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.pushButton_file = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_file.setObjectName("pushButton_file")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_file)
        self.label = QtWidgets.QLabel(self.layoutWidget3)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(41, 70, 60, 16))
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(10, 340, 341, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "单词本生成器"))
        self.pushButton_start.setText(_translate("MainWindow", "开始"))
        self.radioButton_file.setText(_translate("MainWindow", "文件"))
        self.radioButton_clipboard.setText(_translate("MainWindow", "剪切板"))
        self.pushButton_file.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "从文件导入："))
        self.label_2.setText(_translate("MainWindow", "输出模式："))
        self.progressBar.setFormat(_translate("MainWindow", "%v/%m"))
        self.action.setText(_translate("MainWindow", "设置"))
