# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'word_note_generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_input = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_input.setGeometry(QtCore.QRect(30, 90, 221, 361))
        self.textEdit_input.setObjectName("textEdit_input")
        self.textEdit_output = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_output.setGeometry(QtCore.QRect(480, 90, 251, 371))
        self.textEdit_output.setObjectName("textEdit_output")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(300, 490, 75, 23))
        self.pushButton_start.setObjectName("pushButton_start")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 31, 130, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_inputmode = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_inputmode.setObjectName("comboBox_inputmode")
        self.comboBox_inputmode.addItem("")
        self.comboBox_inputmode.addItem("")
        self.comboBox_inputmode.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_inputmode)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(490, 31, 142, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_output_mode = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_output_mode.setObjectName("comboBox_output_mode")
        self.comboBox_output_mode.addItem("")
        self.comboBox_output_mode.addItem("")
        self.comboBox_output_mode.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_output_mode)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "单词本生成器"))
        self.pushButton_start.setText(_translate("MainWindow", "开始"))
        self.label.setText(_translate("MainWindow", "输入源："))
        self.comboBox_inputmode.setItemText(0, _translate("MainWindow", "剪切板"))
        self.comboBox_inputmode.setItemText(1, _translate("MainWindow", "文本框"))
        self.comboBox_inputmode.setItemText(2, _translate("MainWindow", "文件"))
        self.label_2.setText(_translate("MainWindow", "输出模式："))
        self.comboBox_output_mode.setItemText(0, _translate("MainWindow", "文本框"))
        self.comboBox_output_mode.setItemText(1, _translate("MainWindow", "文件"))
        self.comboBox_output_mode.setItemText(2, _translate("MainWindow", "剪切板"))
        self.menu.setTitle(_translate("MainWindow", "设置"))
        self.menu_2.setTitle(_translate("MainWindow", "反馈"))
